name: Code Coverage

on: [push]

jobs:
    phpunit:
        runs-on: ubuntu-latest

        steps:
            -   uses: actions/checkout@v2

            -   name: Install PHP Dependencies
                run: "composer install --no-ansi --no-interaction --no-scripts --no-suggest --prefer-dist"

            -   name: Coverage
                env:
                    XDEBUG_MODE: coverage
                run: composer run coverage